[build]
  publish = "."
  functions = "netlify/functions"

[functions."check-code-supply"]
  schedule = "@daily"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
